# -*- coding: utf-8 -*-
"""Tools_bindings _langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzfNg0C7FDKK4hAm9GnbHMU6HIzkEnjI
"""

import os
os.environ["OPENAI_API_KEY"] = "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"

!pip install -q langchain-openai langchain-core requests

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

# tool create

@tool
def multiply(a: int, b: int) -> int:
  """Given 2 numbers a and b this tool returns their product"""
  return a * b

print(multiply.invoke({'a':3, 'b':4}))

multiply.name

multiply.description

llm = ChatOpenAI()

llm.invoke('hiii')

llm_with_tools = llm.bind_tools([multiply])

query = HumanMessage('can you multiply 3 with 1000')

messages

result = llm_with_tools.invoke(messages)

messages.append(result)

tool_result = multiply.invoke(result.tool_calls[0])

tool_result

messages

llm_with_tools.invoke(messages).content